main.py
from gevent import monkey

monkey.patch_all()
import os

os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

import click
from logging.config import dictConfig
from werkzeug.serving import run_simple


@click.group()
def cli():
    dictConfig({
        'version': 1,
        'formatters': {'default': {'format': '[%(levelname)s] %(asctime)s - %(name)s:%(lineno)d - %(message)s'}},
        'handlers': {'wsgi': {'class': 'logging.StreamHandler', 'stream': 'ext://sys.stdout', 'formatter': 'default'}},
        'root': {'level': 'INFO', 'handlers': ['wsgi']}
    })


@cli.command()
@click.option('--debug/--no-debug', '-d', default=True)
def serve(debug):
    from s3htmlviewer.web import app

    if debug:
        app.debug = True
        return run_simple(os.environ.get("HOST", "0.0.0.0"), int(os.environ.get("PORT", "80")), app, use_debugger=True, use_reloader=True, use_evalex=True, threaded=True)
    else:
        return run_simple(os.environ.get("HOST", "0.0.0.0"), int(os.environ.get("PORT", "80")), app, threaded=True)


if __name__ == '__main__':
    cli()

s3htmlviewer/views/__init__.py
from s3htmlviewer.views.auth import Auth
from s3htmlviewer.views.s3 import S3

s3htmlviewer/views/auth.py
from flask import Blueprint, current_app, redirect, session, url_for, g

from s3htmlviewer.decos import authed, with_user

Auth = Blueprint('auth', __name__, url_prefix='/api/auth')


@Auth.route('/logout', methods=['POST', 'GET'])
@authed
def auth_discord_logout():
    current_app.discord.revoke()
    return redirect(url_for("root"))


@Auth.route('/discord')
def auth_discord():
    return current_app.discord.create_session(scope=["guilds", "identify"], prompt=False)


@Auth.route('/discord/callback')
def auth_discord_callback():
    try:
        current_app.discord.callback()
    except: # noqa
        return redirect(url_for("auth.auth_discord"))

    # Try to get all guilds
    if session.get("next_url", None):
        url = str(session["next_url"])
        del session["next_url"]
        return redirect(url)
    return redirect(url_for("root"))


@Auth.route('/@me')
@with_user
def auth_me():
    data = g.user.__dict__.copy()
    for k in list(data.keys()):
        if k.startswith('_'):
            del data[k]
    data['guilds'] = g.guilds
    return data

s3htmlviewer/views/s3.py
import os

import flask
from flask import Blueprint, current_app, redirect, session, url_for, g, jsonify, request, abort
from minio import S3Error

from s3htmlviewer.decos import with_user, has_permission
from s3htmlviewer.s3util import get_files, get_file

S3 = Blueprint('S3', __name__, url_prefix='/api/s3')


@S3.route("/list")
@with_user
@has_permission
def listendpoint():
    parent = request.args.get('parent')
    allowed = request.args.get('allowed')

    if not allowed:
        allowed = ['folder']

    if not parent:
        parent = None
    return jsonify(list(get_files(parent=parent, allow=allowed))), 200


@S3.route("/file/<path:path>")
@with_user
@has_permission
def fileendpoint(path):
    if not path:
        abort(404, 'File not found')
    try:
        file = get_file(path)
    except S3Error:
        abort(404, 'Backend error')

    # stupid way to match contact type
    resp = flask.Response(file)
    resp.headers['Content-Type'] = file.headers.get('Content-Type')
    return resp

templates/base.jinja
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
        <title>S3 Discord Archive Viewer</title>
        <meta name="theme-color" content="#7289DA">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" integrity="sha512-UJfAaOlIRtdR+0P6C3KUoTDAxVTuy3lnSXLyLKlHYJlcSU8Juge/mjeaxDNMlw9LgeIotgz5FP8eUQPhX1q10A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	    <style>
            .select-dropdown{
                color: white;
                background-color: #37393E;
            }

            ul.dropdown-content.select-dropdown li span {
                color: white;
                background-color: #37393E;
            }

            body {
              background-color: #2F3135;
              color: white;
            }

            .nav-dash, .dash-content {
              padding-left: 300px;
            }

            @media only screen and (max-width : 992px) {
              .nav-dash, .dash-content {
                padding-left: 0;
              }
            }

            #dropdown1 {
              background-color: #37393E;
            }

            #nav-mobile {
              background-color: #24272A;
            }

            #nav-dash {
              background-color: #24272A;
            }

            .btn {
              background-color: #7289DA;
            }

            .btn:visited {
              background-color: #7289DA;
            }

            .btn:hover {
                background-color: rgb(64, 69, 75);
            }

            nav {
              background-color: #2F3135;
              /* z-index: 0; */
            }

            #dashbots {
              color: #7289DA;
              user-select: none;
            }

            @media (max-width:435px) {
                #dashbots {
                  font-size: 13vw;
                }
              }

            .nav-icon {
              vertical-align: middle;
              margin-left: 10px;
            }

            .discord {
              color: #7289DA;
            }

            #main, #listcard {
                background-color: #37393E
            }

            .vertical-align-middle {
                margin: 0px;
                padding:0px;
                float: left;
                position:absolute;
                top: 50%;
                transform: translateY(-50%) translateX(-50%);
                left:50%;
            }

            .icon-block {
              padding: 0 15px;
            }
            .icon-block .material-icons {
                font-size: inherit;
            }
        </style>
    </head>

	<body>
		{% block navbar %}

		{% include 'navbar.jinja' %}

		{% endblock %}

		{% block content %}{% endblock %}

		<!--  Scripts-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/3.35.0/minified.js" integrity="sha512-4onBOReBl8Ahp9q5ckJwB70wFMa1q74/L2TDh/Lpk0f26ftYp7DPM7KXJheocprl4cicFk9ZshZ8V/Gwkv1ccA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.js" integrity="sha512-m2PhLxj2N91eYrIGU2cmIu2d0SkaE4A14bCjVb9zykvp6WtsdriFCiXQ/8Hdj0kssUB/Nz0dMBcoLsJkSCto0Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script>
            M.AutoInit();
            $('.dropdown-trigger').dropdown({coverTrigger: false});
        </script>
        {% block scripts %} {% endblock %}
	</body>
</html>

templates/index.jinja
{% extends "base.jinja" %}
{% block content %}

<main>
    {% if not user %}
        <div class="vertical-align-middle center container">
            <div class="card-panel hoverable" id='main'>
                <h1 id='dashbots'>S3 Discord Archive Viewer</h1>
                <h5 class="header col s12 light grey-text">This site is used to display old archives</h5>
                <br>
            </div>
        </div>
    {% else %}
        <div class="vertical-align-middle center container">
            <div class="card-panel hoverable" id='main'>
                <select aria-label="backup_sel" data-target="dropdown1">>
                    {% for folder in parent_backups %}
                    <option {% if request.args.get('backup_sel') == folder %}selected{% endif %} value="{{ folder }}">{{ folder[:-1] }}</option>
                    {% endfor %}
                    <option disabled {% if 'backup_sel' not in request.args or request.args.get('backup_sel') not in parent_backups %}selected{% endif %}> -- select a backup -- </option>
                </select>
            </div>
        {% if backup_files %}
        <div class="card-panel hoverable" id='main'>
                <select aria-label="backup_file" data-target="dropdown1">>
                    {% for folder in backup_files %}
                    <option {% if request.args.get('backup_file') == folder %}selected{% endif %} value="{{ folder }}">{{ folder.replace(request.args.get('backup_sel'), '').replace('.html', '') }}</option>
                    {% endfor %}
                    <option disabled {% if 'backup_file' not in request.args or request.args.get('backup_file') not in backup_files %}selected{% endif %}> -- select a backup file -- </option>
                </select>
        </div>
        {% endif %}
        {% if request.args.get('backup_file') %}
            <div class="card-panel hoverable" id='main'>
                <iframe src={{ url_for('S3.fileendpoint', path=request.args.get('backup_file')) }} style="width:100%" target="_blank"></iframe>
                <a target="_blank" href={{ url_for('S3.fileendpoint', path=request.args.get('backup_file')) }}><i class="material-icons" id='dash'>open_in_new</i></a>
            </div>
        {% endif %}
        </div>
    {% endif %}
</main>
{% endblock %}

{% block scripts %}
    <script>
        // listener for all selection objects
        document.addEventListener("change", function(e) {
            console.log(`name: ${e.target.ariaLabel}\nchoice: ${e.target.value}`)
            let searchParams = new URLSearchParams(window.location.search);
            if (searchParams.has(e.target.ariaLabel)) {
                if (searchParams.get(e.target.ariaLabel) === e.target.value)
                    return
                searchParams.delete(e.target.ariaLabel)
            }
            searchParams.append(e.target.ariaLabel, e.target.value);
            window.location.search = searchParams.toString();
        });

    </script>
{% endblock %}

templates/navbar.jinja
<ul id="dropdown1" class="dropdown-content">
    <li class='divider' style="background-color:#444649"></li>
    <li>
        <a href="/api/auth/logout"><span style='color:#7289DA'>Logout</span></a>
    </li>
</ul>

<div class='navbar-fixed'>
    <nav class="lighten-1">
        <div class="nav-wrapper container">
            <a id="logo-container" href="/" class="brand-logo">
                <i class="material-icons" id='dash'>home</i>
            </a>

            <ul class="right hide-on-med-and-down">
                {% if not user %}
                <li>
                    <a href="/api/auth/discord" class="waves-effect"><i class="right material-icons" id='dash'>account_circle</i>Login</a>
                </li>
                {% else %}
                <li>
                    <a class="dropdown-trigger waves-effect" href="#!" data-target="dropdown1">{{ user.name }}
                        <img class='circle nav-icon' width='25px' src="{{ user.avatar_url }}">
                    </a>
                </li>
                {% endif %}
            </ul>

            <a href="#!" data-target="nav-mobile" class="button-collapse sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>
    </nav>
</div>


<ul id="nav-mobile" class="sidenav">
    {% if not user %}
    <div class="user-view">
            <div class="background" style='background-color:#2D2F33'></div>
            <a><img class="circle" src="https://cdn.discordapp.com/embed/avatars/0.png"></a>
            <br>
    </div>
    <li><a href="/api/auth/discord" class="waves-effect"><span class="grey-text">Login</span></a></li>
    {% else %}
    <div class="user-view">
        <div class="background" style='background-color:#2D2F33'>
        </div>
        <a><img class="circle" src="{{ user.avatar_url }}" alt="https://cdn.discordapp.com/embed/avatars/0.png"></a>
        <a><span class="grey-text name"><b style='color:white'>{{ user.username}}</b>#{{ user.discriminator }}</span></a>
        <br>
    </div>
    <li><a href="/api/auth/logout" class="waves-effect"><span class="grey-text">Logout</span></a></li>
    <li class='divider' style="background-color:#444649"></li>
    {% endif %}
</ul>